---
- name: Configure Web Server Locally
  hosts: localhost    # Alvo é a própria máquina
  connection: local   # Usa a conexão local, não SSH
  become: yes         # Necessário para instalar pacotes e gerenciar serviços

  tasks:
    - name: Ensure all packages are up to date
      yum:
        name: '*'
        state: latest

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Nginx on Amazon Linux 2
      command: amazon-linux-extras install -y nginx1
      args:
        creates: /usr/sbin/nginx

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Clone website repository
      git:
        repo: 'https://github.com/avanti-dvp/site-exemplo-aws.git' # Pode ser o mesmo repo ou outro
        dest: '/tmp/website'
        clone: yes

    - name: Deploy website files to Nginx document root
      copy:
        src: "/tmp/website/"
        dest: "/usr/share/nginx/html/"
        remote_src: yes # src e dest estão na mesma máquina
        owner: root
        group: nginx
        mode: '0755'
      notify: 
      - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted